# Generated by Django 5.0.7 on 2024-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_payment_on_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Адрес доставки'),
        ),
    ]
