# Generated by Django 5.0.7 on 2024-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_delivery',
            field=models.BooleanField(default=False, verbose_name='Нужна ли доставка'),
        ),
    ]
