# Generated by Django 5.0.7 on 2024-09-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_requires_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='time_create',
        ),
    ]
