# Generated by Django 5.0.7 on 2024-09-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requires_delivery',
        ),
    ]
