# Generated by Django 5.0.7 on 2024-09-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_requires_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
    ]
