# Generated by Django 5.0.7 on 2024-09-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table=None,
        ),
    ]
