# Generated by Django 5.0.7 on 2024-09-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_review_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления'),
        ),
    ]
