# Generated by Django 5.0.7 on 2024-10-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_review_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
