# Generated by Django 5.0.7 on 2024-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Слаг')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='goods__img', verbose_name='Изображение')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, unique=True, verbose_name='email')),
            ],
        ),
    ]
