# Generated by Django 5.0.7 on 2024-09-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя организации')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, unique=True, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Адрес')),
            ],
        ),
        migrations.AlterModelOptions(
            name='stuff',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterField(
            model_name='stuff',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
