# Generated by Django 5.0.7 on 2024-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_alter_stuff_options_alter_stuff_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AddField(
            model_name='contact',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods__img', verbose_name='Изображение'),
        ),
    ]
